name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Release API
        uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: 23f34223-647a-4ddb-a455-7feb56945dab
          heroku_app_name: moia-challenge-be #Must be unique in Heroku
          heroku_email: isaifookhan@gmail.com
        env:
          NODE_ENV: "production"
          HD_APP_BASE: "./src/server"
      - name: Release UI
        uses: akhileshns/heroku-deploy@v3.0.4 # This is the action
        with:
          heroku_api_key: 23f34223-647a-4ddb-a455-7feb56945dab
          heroku_app_name: moia-challenge-fe
          heroku_email: isaifookhan@gmail.com
        env:
          NODE_ENV: "production"
          HD_APP_BASE: "./src/ui"
